In [1]:
import numpy as np
print(np.__version__)

2.5.1


In [4]:
# 1-D Array
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
# 2-D Array
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
2


In [9]:
# 3-D Array
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print(c.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [14]:
# Other array creation functions

In [13]:
d=np.zeros((2,3))
print(d)
print(d.ndim)

e=np.ones((3,3))
print(e)
print(e.ndim)

[[0. 0. 0.]
 [0. 0. 0.]]
2
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2


In [15]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.arange(0,5,4)

array([0, 4])

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
# Data types

In [22]:
a=np.array([1,2,3])
print(a.dtype)

int64


In [23]:
b=np.array([1,2,3], dtype=np.float64)
print(b.dtype)

float64


In [24]:
c=a.astype(np.float64)
print(c)

[1. 2. 3.]


In [25]:
# shape, dimensions, and size

In [26]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64


In [30]:
# Reshaping arrays
a=np.arange(12)
print(a)
b=a.reshape(3,4)
print(b)
print(b.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2


In [31]:
c=a.reshape(2,-1) # -1 lets numpy infer that dimension
print(c)
print(c.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)


In [33]:
# flattening of arrays
arr=np.array([[1,2],[3,4]])
print(arr)
print(arr.flatten()) # returns a copy
print(arr.ravel()) # returns a view when possible

[[1 2]
 [3 4]]
[1 2 3 4]
[1 2 3 4]


In [34]:
# Array Operations

In [37]:
# arithematic
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[0 0 0 0]
[ 100  400  900 1600]


In [38]:
# comparison
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a>b)
print(a==b)
print(a<=2)

[False False False False]
[False False False False]
[ True  True False False]


In [43]:
# ufunc(universal functions)- operates elements wise on arrays
# ufuncs support broadcasting, type casting, and optional output arrays for in-place computation

In [42]:
a=np.array([1,2,3,4])
b=np.array([4,3,2,1])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.power(a,2))
print(np.mod(a,b))
print(np.abs(np.array([-1,-2,3])))

[5 5 5 5]
[-3 -1  1  3]
[4 6 6 4]
[0.25       0.66666667 1.5        4.        ]
[ 1  4  9 16]
[1 2 1 0]
[1 2 3]


In [55]:
# Indexing and Slicing. In basic slicing it returns a reference

In [45]:
a=np.array([10,20,30,40,50])
print(a[3])

b=np.array([[1,2,3],[4,5,6]])
print(b[1,2])

40
6


In [46]:
print(a[-1]) # negative indexing

50


In [47]:
a=np.array([10,20,30,40,50])
print(a[1:4])
print(a[:3])
print(a[2:])

[20 30 40]
[10 20 30]
[30 40 50]


In [49]:
a=np.arange(10)
print(a[::2])
print(a[1:8:2])
print(a[::-1]) # reverse the array

[0 2 4 6 8]
[1 3 5 7]
[9 8 7 6 5 4 3 2 1 0]


In [53]:
# fancy indexing- it returns a copy
a=np.array([10,20,30,40,50])
idx=[0,2,4]
print(a[idx])

[10 30 50]


In [54]:
# boolean indexing/ filtering- it returns a copy
a=np.array([10,15,20,25,30])
mask=a>18
print(mask)
print(a[mask])
print(a[a%10==0])

[False False  True  True  True]
[20 25 30]
[10 20 30]


In [56]:
# to check entire numpy directory
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [58]:
# mathematical functions
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.min(a))
print(np.max(a))
print(np.percentile(a,75))
print(np.sqrt(a))
print(np.log(a))
print(np.exp(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

55
5.5
5.5
2.8722813232690143
8.25
1
10
7.75
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566  0.64836083]


In [59]:
# Array Manipulation

In [60]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a)
print(b)
print(np.concatenate([a,b]))
print(np.vstack([a,b])) # stack as rows - shape (2,3)
print(np.hstack([a,b])) # stack horizontally
print(np.stack([a,b], axis=0)) # new axis - shape (2,3)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [64]:
# split
a=np.arange(9)
print(a)
np.split(a,3)

[0 1 2 3 4 5 6 7 8]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [69]:
# insert, update, delete - they make a copy, do not modify original array
a=np.array([1,2,3])
print(a)
print(np.append(a,[4,5]))
print(a)
print(np.insert(a,1,99))
print(a)
print(np.delete(a,0))
print(a)

[1 2 3]
[1 2 3 4 5]
[1 2 3]
[ 1 99  2  3]
[1 2 3]
[2 3]
[1 2 3]


In [74]:
# sort, unique, reverse - they make a copy, do not modify original array
a=np.array([3,1,4,1,5,9,2])
print(a)
b=np.sort(a)
print(b)

print(np.unique(a))
print(a[::-1])

[3 1 4 1 5 9 2]
[1 1 2 3 4 5 9]
[1 2 3 4 5 9]
[2 9 5 1 4 1 3]


In [81]:
# Broadcasting - In NumPy is a powerful mechanism that allows arithmetic operations to be performed on arrays of different shapes
# Two dimensions are compatible if: They are equal in size, One of them is exactly 1.

In [80]:
matrix=np.array([[1,2,3],[4,5,6]])
row_add=np.array([10,20,30])
print(matrix)
print(row_add)
print(matrix+row_add)

[[1 2 3]
 [4 5 6]]
[10 20 30]
[[11 22 33]
 [14 25 36]]
